---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: refacto
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 5m0s
  path: ./clusters/refacto/refacto/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
